### ISSUE TITLE
Enabling StatsD by setting the flag USE_STATSD=true

### ISSUE THREAD

**Issue by yubofredwang** [envoyproxy/ratelimit#126]
I currently have my dd-agent running on localhost:8125 accepting UDP traffic. However, I think after setting the flag to true. The program is trying to connect through TCP which is causing a connection refused error.
I looked up the flag in the code base and did not find where it being used. Can someone shed a light on how to solve this?
Besides, I am also trying to use see the stats through gostats. However, I not familiar with it. Should write another program to accept the data or should I modify the current code to be able to see the stats?
Thanks ahead for any info provided.

**Comment by indrekj** [comment]
Had the same trouble. It looks that underneath gostats is being used which can be controlled using environment variables. Settings `STATSD_PROTOCOL=udp` worked for me.
