### ISSUE TITLE
New tagged release

### ISSUE THREAD

**Issue by CheesyFeet** [envoyproxy/ratelimit#128]
Now that we have Docker images being published publicly, are there any plans to release a new tagged version so it's possible to pin against a specific version? 

At the moment I can only see the 'master' image and would like to specify a particular release number.

Thanks

**Comment by mattklein123** [comment]
We can take a release. @stevesloka did you have any further changes you wanted to make in the near term?

**Comment by stevesloka** [comment]
Nope I think all is well for now. When you tag the release, it should build the tagged version automatically as long as it starts with a 'v'.

**Comment by mattklein123** [comment]
https://hub.docker.com/layers/envoyproxy/ratelimit/v1.4.0/images/sha256-71081616da3e365eb8bb4751c1d187041ad28ab17719ff0e70745cb0f5c80412?context=repo

Thanks @stevesloka!!!
