### ISSUE TITLE
Proposal: more permissive shouldRateLimit-to-config matching

### ISSUE THREAD

**Issue by dweitzman** [envoyproxy/ratelimit#134]
We're looking into using envoyproxy/ratelimit but have some concerns that configuring limits and checking limits is more intertwined than we'd want.

Suppose you want to have a few different rate limits that might share common fields, like one on (account, endpoint) and one on (account, ip)

As currently implemented, a person calling into the rate limiter API would need to make a request that's very aware of exactly which rate limits exist and apply:

```
rate_limit_request [
  descriptor(account=123, endpoint=foo_api_method),
  descriptor(account=123, ip=1.2.3.4)
]
```

And then if you want to make a new rate limit on another dimension like (account_type=free, endpoint_type=write) you would need to go back and update the rate_limit_request yet again to include it in exactly that order:

```
rate_limit_request [
  descriptor(account=123, endpoint=foo_api_method),
  descriptor(account=123, ip=1.2.3.4)
  descriptor(account_type=free, endpoint_type=write)
]
```

The proposal is for more permissive rate limit matching where instead of three different descriptors as above you could just have one:

```
rate_limit_request [
  descriptor(account=123, endpoint=foo_api_method, ip=1.2.3.4, account_type=free, endpoint_type=write),
]
```

A limit configured for (account, endpoint) would match this descriptor, or (account, ip), or (account_type, endpoint_type), or any subset of keys from the provided descriptor.

To do the matching, instead of iterating through descriptors to find matching limits it would likely involve looking through configured limits to see which ones have all the necessary keys present in a descriptor, restricted to a given domain.

The behavior change could be opt-in to avoid impacting existing users, either with a request flag or a server configuration option.

The benefit going forward would be a separation of concerns between how rate limiting is configured vs how limits are queried. A shouldRateLimit() call would essentially say, "here are all the fields that might be useful for rate limiting" and if there's an active incident where it becomes useful to introduce a new rate limit based on IP address that would be a standalone configuration change to rate limits without any need for a corresponding change to the service that's being limited

Thoughts? Feelings? Concerns? Hopes? Dreams? Fears?

**Comment by mattklein123** [comment]
> Thoughts? Feelings? Concerns? Hopes? Dreams? Fears?

The downside of this type of configuration is that it is very difficult to reason about what limits are going to be applied from looking at a descriptor and the configuration. There may also be perf implications of the lookup datastructures in the server. With that said, this sounds like a reasonable feature to add so if would like an API variant that allows this type of matching I'm not opposed.
