### ISSUE TITLE
Proposal to contribute memcache support in addition to redis

### ISSUE THREAD

**Issue by dweitzman** [envoyproxy/ratelimit#140]
We're interested in contributing memcache support as an optional alternative to redis for the ratelimit k/v store. Memcache is what we normally use for caching, and it's what our storage & caching team is comfortable with and provides as a service to us.
Does this sound like a totally crazy and useless contribution that would be rejected if we mailed a clean and clear PR?

**Comment by mattklein123** [comment]
> Does this sound like a totally crazy and useless contribution that would be rejected if we mailed a clean and clear PR?

Sure sounds fine to me. IIRC the cache abstraction should make it relatively easy to do this.
