### ISSUE TITLE
Golang gRPC Stubs or docs on how to generate?

### ISSUE THREAD

**Issue by andytsnowden** [envoyproxy/ratelimit#169]
Are there any already generated subs for the envoyproxy protobuf files? Or docs somewhere that show how to do this?  I want to use the gRPC interface but I don't see a simple way to generate the stubs based on the proto file.

**Comment by mattklein123** [comment]
Right now we pull the generated protos in from go control plane. See for example here: https://github.com/envoyproxy/ratelimit/blob/master/src/client_cmd/main.go. cc @kyessenov

**Comment by andytsnowden** [comment]
> 
> 
> Right now we pull the generated protos in from go control plane. See for example here: https://github.com/envoyproxy/ratelimit/blob/master/src/client_cmd/main.go. cc @kyessenov

Thanks for this, I completely missed it when looking at those files earlier.
