### ISSUE TITLE
Return NEAR_LIMIT as a response code

### ISSUE THREAD

**Issue by clarkds14** [envoyproxy/ratelimit#171]
For clients that want to collect metrics on ratelimit responses, this is useful to return back.

HIT/OVER_LIMIT/NEAR_LIMIT stats that are emitted from the ratelimit service statically match what's configured. For example, requests that match against the default configuration will all get bucketed together for the purpose of stats. So for instance, if there is a default configuration for `key=service` and a request for `key=service,value=foo,hits=1` and `key=service,value=var,hits=1`, the value of 2 will be emitted for `key=service` HITS metric. This may be fine for monitoring the ratelimit service itself but clients will want to monitor the NEAR_LIMIT stat as well.

**Comment by mattklein123** [comment]
Can you do an API proposal to enable this feature and we can discuss?
