### ISSUE TITLE
Push images on very main commit

### ISSUE THREAD

**Issue by JaveriaK** [envoyproxy/ratelimit#174]
Our environment uses a UDP statsd collector. In ref to: https://github.com/envoyproxy/ratelimit/pull/157 , since the actual changeset that supported a UDP sink (https://github.com/lyft/gostats/pull/95) was merged after `envoyproxy/ratelimit:v1.4.0` was cut; can we please get a newer tag upstream for the ratelimit image?
This can done with a local build but we'd prefer pulling an official upstream tagged image.

**Comment by mattklein123** [comment]
I would really like to get out of the business of having to explicitly tag releases.

@stevesloka can we potentially push images on every main commit tagged by SHA? I think that would be a lot easier given the relatively small number of commits we have on this project.

**Comment by stevesloka** [comment]
@mattklein123 yup we can do that! I'm happy to put a PR together to do that.

**Comment by mattklein123** [comment]
Thank you!

**Comment by gburton1** [comment]
It's nice having an image available for every SHA, but it would still be nice to have releases at some cadence (quarterly?). For use cases that have Federal compliance restrictions, release versioning is the official way to prove that the latest recommended version of a project is being used (a requirement when there are open CVEs against the project, which there typically is). When SHAs are used as a stand-in for official releases, then every change signals an official release that triggers an upgrade requirement. So even if you have a change that just edits the README, technically it's a new release that requires an upgrade. And with Dependabot, the commit history is pretty active in the past couple months. Anyway, for your consideration, it would be convenient to have a low-effort release cadence for this use case 🙏
