### ISSUE TITLE
Proposal: Cut new version

### ISSUE THREAD

**Issue by wwillsey** [envoyproxy/ratelimit#175]
Hi, Im proposing tagging a new release v1.5.0, as there have been a number of changes since March 16 (v1.4.0), and It would be good to be able to specify a tag rather than latest master when building this project for use. 

Is there a cadence to the releases that perhaps I'm not aware of? 

Thanks!

-Will

**Comment by mattklein123** [comment]
Please see https://github.com/envoyproxy/ratelimit/issues/174
