### ISSUE TITLE
error: signal: segmentation fault (core dumped)

### ISSUE THREAD

**Issue by nayan-kalita** [envoyproxy/ratelimit#180]
istio version 1.7.3

ingress gateway is crashing after deploying rate limit service.

The following errors are seen in the logs of ingress -

warning	envoy config	gRPC config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: Error adding/updating listener(s) 0.0.0.0_8080: Proto constraint validation failed (RateLimitValidationError.Domain: ["value length must be at least " '\x01' " bytes"]): 
0.0.0.0_8443: Proto constraint validation failed (RateLimitValidationError.Domain: ["value length must be at least " '\x01' " bytes"]):

info	sds	resource:ROOTCA connection is terminated: rpc error: code = Canceled desc = context canceled
error	sds	Remote side closed connection
info	sds	resource:default connection is terminated: rpc error: code = Canceled desc = context canceled
error	sds	Remote side closed connection
error	Epoch 0 exited with error: signal: segmentation fault (core dumped)
info	No more active epochs, terminating

**Comment by ysawa0** [comment]
This sounds like a config issue. I'm not as familiar with Istio config but could you post it and I can try and help debug.

**Comment by mattklein123** [comment]
Please open this issue in the Istio project.
