### ISSUE TITLE
Redis counter increases for blocked calls 

### ISSUE THREAD

**Issue by jdomag** [envoyproxy/ratelimit#185]
**Issue:**
I will describe it by example. 
We limit calls to our service per customer. By default customer has 10 requests/hour. Client can ask to expand this limit for additional charge.  
Client did 50 requests to our service out of which 40 was blocked. He asked us to increase a limit to 20, so we redeployed rateLimit service with new limit - 20req/hour. However redis has single key for both accepted and denied calls, so even if we changed limit to 20 requests, client can't do additional 10 requests during same hour because counter in redis shows 50 call and rateLimit service blocks the calls.
It's not a case when you limit calls per second or minute. But we plan to use limits per week or even month and definitely needs an ability to increase a quota during that time and not make a client wait another month to see an effect.

**Comment by mattklein123** [comment]
I can't think of an easy way to fix this without a bunch more state that would be consumed by both the service and the caching infrastructure. If you have any concrete suggestions happy to mark this help wanted.

**Comment by jdomag** [comment]
Hi, 
As you mentioned I think the best would be to  add some more states e.g. total numer of requests, number of allowed requests before limit etc.
But maybe a good start would be to stop increasing total number of hits in cache engine when the limit is reached? We'll loose the knowledge about the total number of requests, but still it seems to bring more value than just a stats.

**Comment by mattklein123** [comment]
> But maybe a good start would be to stop increasing total number of hits in cache engine when the limit is reached? We'll loose the knowledge about the total number of requests, but still it seems to bring more value than just a stats.

I'm not sure how you would do this when using multiple service instances. You would would need some type of CAS (compare and swap) in the cache.

We already do local caching of over limit, which shouldn't increment the cache anymore. Perhaps this is good enough?

**Comment by jdomag** [comment]
@mattklein123 
Is the local caching available in v1.4.0? I use this version and redis cache is incremented with every over limit hit.
