### ISSUE TITLE
how to run example?

### ISSUE THREAD

**Issue by jbj616** [envoyproxy/ratelimit#195]
I tried to run docker compose and i execute curl command, i cannot find response

1. `docker-compose -f docker-compose-example.yml up`
2. `curl localhost:8888/test
curl localhost:8888/header -H "foo: foo" # Header based
curl localhost:8888/twoheader -H "foo: foo" -H "bar: bar" # Two headers
curl localhost:8888/twoheader -H "foo: foo" -H "baz: baz"
curl localhost:8888/twoheader -H "foo: foo" -H "bar: banned" # Ban a particular header value`

result:
`curl: (7) Failed to connect to localhost port 8888: Connection refused`

**Comment by ysawa0** [comment]
There was a reference to v2 api still left in the config. I pushed #196 which has the right V3 filter. Can you try giving that a go.

**Comment by jbj616** [comment]
thanks! 
```
curl localhost:8888/test
Hellow World
```
