### ISSUE TITLE
multiple memcached server support

### ISSUE THREAD

**Issue by bobo** [envoyproxy/ratelimit#205]
Im trying out the memcached support, and have trouble using more than one server.

having:
ENV MEMCACHE_HOST_PORT=host1t:11211,host2:11211,host3:11211
ENV BACKEND_TYPE=memcache

doesnt seem to work out of the box.
I looked into the memcache client used and it does support multiple servers (and handles key paritioning).

i tried the following change and then it seems to work atleast. 
But maybe im missing something and there is another way of configuring multiple memcache servers?

Index: src/memcached/cache_impl.go
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/memcached/cache_impl.go b/src/memcached/cache_impl.go
--- a/src/memcached/cache_impl.go	(revision 6f5de117a9e59e80f3dbb05ad8c47d1cea85b87f)
+++ b/src/memcached/cache_impl.go	(date 1610458313644)
@@ -19,6 +19,7 @@
 	"context"
 	"math/rand"
 	"strconv"
+	"strings"
 	"sync"
 
 	"github.com/coocood/freecache"
@@ -186,7 +187,7 @@
 func NewRateLimitCacheImplFromSettings(s settings.Settings, timeSource utils.TimeSource, jitterRand *rand.Rand,
 	localCache *freecache.Cache, scope stats.Scope) limiter.RateLimitCache {
 	return NewRateLimitCacheImpl(
-		memcache.New(s.MemcacheHostPort),
+		memcache.New(strings.Split(s.MemcacheHostPort,",")...),
 		timeSource,
 		jitterRand,
 		s.ExpirationJitterMaxSeconds,

**Comment by dweitzman** [comment]
That seems reasonable to add

Memcache support is quite recent. I didn't add multiple host support in the initial version since we're running mcrouter on localhost to handle cluster management
