### ISSUE TITLE
hot reload with a same domain is not supported.

### ISSUE THREAD

**Issue by anannaya** [envoyproxy/ratelimit#206]
l am using `RUNTIME_WATCH_ROOT` using hot reload the configuration. Is it possible to update the same domain name ?

level=error msg="error loading new configuration from runtime: config-1.yaml: config file cannot have empty domain"
time="2021-01-15T11:30:13Z" level=error msg="error loading new configuration from runtime: config.yaml: duplicate domain 'vhost-ratelimit' in config file"
time="2021-01-15T11:30:13Z" level=error msg="error loading new configuration from runtime: config.yaml: duplicate domain 'vhost-ratelimit' in config file"
time="2021-01-15T11:30:13Z" level=error msg="error loading new configuration from runtime: config.yaml: duplicate domain 'vhost-ratelimit' in config file"
time="2021-01-15T11:31:22Z" level=error msg="error loading new configuration from runtime: config-1.yaml: config file cannot have empty domain"

**Comment by ysawa0** [comment]
@anannaya Can you post your settings/env vars and config directory structure?

**Comment by anannaya** [comment]
@ysawa0 hot reload is working fine. I need to upload the different discriptors with same same domain name.

**Comment by anannaya** [comment]
Below changes made it working , I feel this is valid usecase of adding new descriptors under same domain using new config files , especially when the ratelimited at ingress layer.
`
 git diff
diff --git a/src/config/config_impl.go b/src/config/config_impl.go
index e19b5ce..4b0b775 100644
--- a/src/config/config_impl.go
+++ b/src/config/config_impl.go
@@ -221,15 +221,18 @@ func (this *rateLimitConfigImpl) loadConfig(config RateLimitConfigToLoad) {
                panic(newRateLimitConfigError(config, "config file cannot have empty domain"))
        }

+       logger.Debugf("loading domain: %s", root.Domain)
        if _, present := this.domains[root.Domain]; present {
-               panic(newRateLimitConfigError(
-                       config, fmt.Sprintf("duplicate domain '%s' in config file", root.Domain)))
+               logger.Infof("Duplicate domain '%s' ,updating", root.Domain)
+               this.domains[root.Domain].loadDescriptors(config, root.Domain+".", root.Descriptors, this.statsScope)
+               //      panic(newRateLimitConfigError(
+               //              config, fmt.Sprintf("duplicate domain '%s' in config file", root.Domain)))
+       } else {
+               newDomain := &rateLimitDomain{rateLimitDescriptor{map[string]*rateLimitDescriptor{}, nil}}
+               newDomain.loadDescriptors(config, root.Domain+".", root.Descriptors, this.statsScope)
+               this.domains[root.Domain] = newDomain
        }

-       logger.Debugf("loading domain: %s", root.Domain)
-       newDomain := &rateLimitDomain{rateLimitDescriptor{map[string]*rateLimitDescriptor{}, nil}}
-       newDomain.loadDescriptors(config, root.Domain+".", root.Descriptors, this.statsScope)
-       this.domains[root.Domain] = newDomain
 }

 func (this *rateLimitConfigImpl) descriptorToKey(descriptor *pb_struct.RateLimitDescriptor) string {
`

**Comment by anannaya** [comment]
@ysawa0   Can you pls help me with this request?

**Comment by ysawa0** [comment]
@anannaya I'm not sure what the intent was in preventing multiple files with the same domain. Guessing it was a design choice of one file == one domain to keep things consistent. I haven't had to have multiple files with same domain but I could see it being useful for some. I suggest you open a PR and I can help review.

**Comment by anannaya** [comment]
@ysawa0 will submit a PR ,Thanks.

**Comment by anannaya** [comment]
@ysawa0  Created. a PR https://github.com/envoyproxy/ratelimit/pull/209/files, Pls review.
