### ISSUE TITLE
How can i do pattern matching on descriptor values?

### ISSUE THREAD

**Issue by stansa** [envoyproxy/ratelimit#235]
It would be good to have either prefix match or regex for descriptor value matching.
Is there a workaround to achieve the same for now?

**Comment by repl-david-winiarski** [comment]
The supported way is to apply that type of filtering on the envoy instance and return a descriptor to be rate limited on. For example you could regex match against a header value in envoy and return a specific descriptor if there's a match. You would then use that descriptor in your rate limits.

**Comment by stansa** [comment]
Yes I did think about it - but the issue I'm not able to extract part of the header value and send that over.

For example if I'm trying to header value match on Paths starting with either of the following. The prefix for the  path can be either abc or xyz but there could several variation for the suffix 123.

/abc/123
/xyz/123
/abc/234
/xyz/234
...

I would like to extract and only send the suffix to the Ratelimiter and configure of the suffixes only.

**Comment by mattklein123** [comment]
Right now the service essentially builds a map so lookups are efficient. We could support prefix/postfix via trie, or potentially regex via linear scan, but it needs some thinking. I think this one will need a design proposal for further discusssion?
