### ISSUE TITLE
Ability to increment "request" counter by value > 1

### ISSUE THREAD

**Issue by sirianni** [envoyproxy/ratelimit#255]
We have a use case where we would like to rate limit based on a "cost" associated with each request (calculated based on request specific attributes) that is not always `1`.

It does not currently seem possible using the ratelimit gRPC interface to specify a value other than `1` by which the counters should be incremented.  Opening this up as a feature request for discussion.

**Comment by patramsey** [comment]
@sirianni does `HitsAddend ` not work for you?

https://github.com/envoyproxy/ratelimit/blob/main/src/client_cmd/main.go#L78

**Comment by sirianni** [comment]
I think it should!  I missed that parameter when looking at the RPC. Thanks @patramsey !
