### ISSUE TITLE
Cut a new release

### ISSUE THREAD

**Issue by johanbrandhorst** [envoyproxy/ratelimit#257]
Hi, great project!

I'm a little concerned that there seems to have been a lot of activity since the last release, and there hasn't been a new release yet. I'm also confused about the plans for the deprecation of the v2 API as described in the README - we haven't seen a v2.0.0 yet, though the README talks about it in past tense, when is that planned?

**Comment by mattklein123** [comment]
Unfortunately the project doesn't have resources to do releases. We ship docker images for every main commit. I believe the v2 deprecation README is out of date so we should fix that.

**Comment by johanbrandhorst** [comment]
The README has not been updated.

**Comment by johanbrandhorst** [comment]
Still not fixed

**Comment by mattklein123** [comment]
Sorry we don't have the resources to do releases, we publish images on every main commit.

**Comment by johanbrandhorst** [comment]
> Unfortunately the project doesn't have resources to do releases. We ship docker images for every main commit. I believe the v2 deprecation README is out of date so we should fix that.

Apologies for the confusion, the issue was left open because you agreed that the README could do with updating.
