### ISSUE TITLE
Getting 500 error code while using Redis-cluster

### ISSUE THREAD

**Issue by Naveen-nimmala** [envoyproxy/ratelimit#265]
When i use single redis instance with service its working as expected but when i use **redis-sentinal or redis-cluster**, its giving 500 response code sometimes why is that. am missing anything? im using this Redis-cluster(https://github.com/bitnami/charts/tree/master/bitnami/redis-cluster)  and updated **REDIS_URL** with redis-cluster service. 

500 response code:
```
HTTP/2 500
server: nginx
date: Mon, 21 Jun 2021 11:32:59 GMT
via: 1.1 google
alt-svc: clear
```
sometimes 429:
```
HTTP/2 429
server: nginx
date: Mon, 21 Jun 2021 11:32:45 GMT
x-envoy-ratelimited: true
via: 1.1 google
alt-svc: clear
```

**Comment by deepthawtz** [comment]
you look at logs? iirc when using redis in cluster mode you need to set additional environment variables.

**Comment by Naveen-nimmala** [comment]
can we have any example setup for it

**Comment by Naveen-nimmala** [comment]
getting below error when i set set additional environment variables.

```
        - name: REDIS_SOCKET_TYPE
          value: tcp
        - name: REDIS_URL
          value: redis:6379
        - name: REDIS_PERSECOND
          value: "true"
        - name: REDIS_PERSECOND_SOCKET_TYPE
          value: tcp
        - name: REDIS_PERSECOND_URL
          value: 10.11.0.1:6379,10.12.3.4:6379
        - name: USE_STATSD
          value: "false"
```

`time="2021-06-22T08:58:59Z" level=warning msg="statsd is not in use"
{"@message":"runtime changed. loading new snapshot at /data/ratelimit","@timestamp":"2021-06-22T08:58:59.480363199Z","level":"debug"}
{"@message":"runtime: processing /data/ratelimit","@timestamp":"2021-06-22T08:58:59.480486416Z","level":"debug"}
{"@message":"runtime: processing /data/ratelimit/config","@timestamp":"2021-06-22T08:58:59.480539013Z","level":"debug"}
{"@message":"runtime: processing /data/ratelimit/config/config.yaml","@timestamp":"2021-06-22T08:58:59.4805558Z","level":"debug"}
{"@message":"runtime: adding key=config.config.yaml value=domain: ratelimit-service\ndescriptors:\n  - key: header_match\n    value: vm_path_ip\n    descriptors:\n      - key: remote_address\n        rate_limit:\n          unit: minute\n          requests_per_unit: 5\n\n  - key: header_match\n    value: cf_path_ip\n    descriptors:\n      - key: remote_address\n        rate_limit:\n          unit: minute\n          requests_per_unit: 5\n uint=false","@timestamp":"2021-06-22T08:58:59.480604983Z","level":"debug"}
**{"@message":"connecting to redis on 10.11.0.1:6379,10.12.3.4:6379 with pool size 10","@timestamp":"2021-06-22T08:58:59.482049352Z","level":"warning"}
{"@message":"Implicit pipelining enabled: false","@timestamp":"2021-06-22T08:58:59.482084291Z","level":"debug"}
panic: dial tcp: address 10.11.0.1:6379,10.12.3.4:6379: too many colons in address**

goroutine 1 [running]:
github.com/envoyproxy/ratelimit/src/redis.checkError(...)
        /ratelimit/src/redis/driver_impl.go:51
github.com/envoyproxy/ratelimit/src/redis.NewClientImpl(0xd6ca20, 0xc0004245a0, 0x0, 0x0, 0x0, 0xb0264b, 0x6, 0xc00003c054, 0x1e, 0xa, ...)
        /ratelimit/src/redis/driver_impl.go:113 +0xbf9
github.com/envoyproxy/ratelimit/src/redis.NewRateLimiterCacheImplFromSettings(0x0, 0x0, 0xac1983, 0x7, 0x1f90, 0xaca9c8, 0x7, 0x1f91, 0xacbfac, 0x7, ...)
        /ratelimit/src/redis/cache_impl.go:17 +0x2e9
github.com/envoyproxy/ratelimit/src/service_cmd/runner.createLimiter(0xd69ba0, 0xc000416bb0, 0x0, 0x0, 0xac1983, 0x7, 0x1f90, 0xaca9c8, 0x7, 0x1f91, ...)
        /ratelimit/src/service_cmd/runner/runner.go:52 +0x26d
github.com/envoyproxy/ratelimit/src/service_cmd/runner.(*Runner).Run(0xc0000a9440)
        /ratelimit/src/service_cmd/runner/runner.go:107 +0x3df
main.main()
        /ratelimit/src/service_cmd/main.go:10 +0x144`

**Comment by Naveen-nimmala** [comment]
Issue has been resolved by updating REDIS_TYPE ENV as a cluster. Its mandatory option while we go for sentinal or cluster option like below

- name: REDIS_TYPE
   value: "cluster"

**Comment by renuka-fernando** [comment]
Hi @Naveen-nimmala
I got this issue: "panic: cannot decode redis array into string"
Any idea on this https://github.com/envoyproxy/ratelimit/issues/351
