### ISSUE TITLE
Which algorithm ratelimit process is using ?

### ISSUE THREAD

**Issue by santinoncs** [envoyproxy/ratelimit#269]
I am not able to find in the documentation which strategy is using the process to rate-limit.

Token bucket, Leaky bucket , Fixed window, Sliding window

thanks

**Comment by chrishowell** [comment]
It's Fixed Window at the moment:
https://github.com/envoyproxy/ratelimit/blob/edab0ecf66e186cf81459368a54990489a2c49e8/src/limiter/cache_key.go#L73
There's a PR for Sliding Window that's been open for many months, gone stale and been closed.

**Comment by santinoncs** [comment]
And why we are not considering token or leaky bucket as we do in local rate limit?
What would be the difference? I don't think consistency is needed here.
