### ISSUE TITLE
Missing ratelimit_service_config_load_error metrics counter

### ISSUE THREAD

**Issue by xuanzhong** [envoyproxy/ratelimit#274]
Both ratelimit_service_config_load_success and ratelimit_service_config_load_error metrics are In the statsd configmap, but when querying the :9102/metrics, only ratelimit_service_config_load_success counter available.

**Comment by ysawa0** [comment]
I checked the statsd exporter config and see two entries for the err metric:
https://github.com/envoyproxy/ratelimit/blob/main/examples/prom-statsd-exporter/conf.yaml#L85-L90
@xuanzhong can you try removing the duplicate and see if that works?

**Comment by xuanzhong** [comment]
@ysawa0  thanks for looking into this issue. I noticed the duplicates and removed that before I raised the ticket, and the metric didn't work after removing the duplicate.

**Comment by xuanzhong** [comment]
@ysawa0  I verified that lastest statsd config worked. I can see the ratelimit_service_config_load_error metrics now. Thanks for the fix!

**Comment by xuanzhong** [comment]
Issue fixed.
