### ISSUE TITLE
Proposal: Shadow mode

### ISSUE THREAD

**Issue by jespersoderlund** [envoyproxy/ratelimit#293]
It would be very helpful to roll-out rate limiting on existing systems with the help of a shadow-mode where the logic and statistics are run exactly as if the limits would have been in place, but where the response is always OK.

It has been added in a fork by https://github.com/replicon/ratelimit/pull/12 by @repl-david-winiarski and would be great to have something like this  integrated into the upstream.

The solution selected by replicon is to have a `shadowmode: true` attribute in the rate limiting definitions so that it can be selectively applied.

**Comment by mattklein123** [comment]
Sure makes sense to me.

**Comment by jespersoderlund** [comment]
Working on a PR inspired by replicon's fork. It's a bit intertwined with additional changes so but I'll push for review in a day or two hopefully

**Comment by jespersoderlund** [comment]
Thanks
