### ISSUE TITLE
How to read metrics from ratelimit serivce? 

### ISSUE THREAD

**Issue by eanton86** [envoyproxy/ratelimit#309]
We use the ratelimit service in envoy mesh with standard configuration, USE_STATSD set to false. 
Is there any way to read metrics from ratelimit service without using statsd server? gostats documentation doesn't tell much about that.

**Comment by zakhenry** [comment]
@eanton86 what was the solution to this? I'm finding the docs lacking for what to do in an environment that doesn't have statsd
