### ISSUE TITLE
Remote configuration of RateLimit

### ISSUE THREAD

**Issue by IoakeimSamarasGR** [envoyproxy/ratelimit#319]
As stated in the README file, the Ratelimit service uses a library written by Lyft called goruntime to do configuration loading.

I would like to ask if there is a plan to also support remote configuration, for example by using gRPC.

Thank you in advance.

**Comment by ysawa0** [comment]
While that's a good idea, I don't think that is in the works. Maybe a form of XDS could be used to implement it?

**Comment by IoakeimSamarasGR** [comment]
Hi,

yes, I was also thinking that the xDS protocol can be used for this purpose in order for the descriptors and rate limit resources to be discovered. Thanks for the response.
