### ISSUE TITLE
Can multiple ratelimits use the same redis cluster?

### ISSUE THREAD

**Issue by mengxialong** [envoyproxy/ratelimit#327]
I want to deploy the following pod in k8s:
1   envoy
2   ratelimit 
3   redis

For high availability, I consider the following settings:
1 envoy and ratelimit's Replica is set to multiple (e.g. 2)
2 redis is set to cluster

The use case should look like this:
1 The client's request reaches a pod in envoy through the load balancer
2 envoys called a pod of the ratelimit in order to determine whether the rate limit was exceeded
3 ratelimit called the redis cluster for judgment
Obviously, there may be multiple ratelimits using the same redis cluster

Can you tell me that multiple ratelimits can use the same redis cluster? Need some special settings?

**Comment by jespersoderlund** [comment]
It should be possible if you use different rate limit prefixes using the environment variable `CACHE_KEY_PREFIX`
