### ISSUE TITLE
Provide support to enable authentication for the ratelimit gRPC service

### ISSUE THREAD

**Issue by iam-nagarajan** [envoyproxy/ratelimit#335]
The ratelimit service does not have options to enforce authentication for requests. 
This could enable some other rogue services/client which has access to this rate limit service to hit this service with different descriptors to create limit exceeded for the descriptor combination without the actual request from end user coming into the system.

**Comment by harsimranmaan** [comment]
One way of doing this is via mTLS. But that support is also lacking in the service today. I was going to file an enhancement request with a similar request before I saw this issue.
