### ISSUE TITLE
Metric to measure ratelimit service's availability.

### ISSUE THREAD

**Issue by kewshah4** [envoyproxy/ratelimit#372]
To. measure the service's availability, we need total number of requests received by the service, and total number of requests which errored out and could not be served. 
Total number of requests can be obtained through this metric - `ratelimit_server.ShouldRateLimit.total_requests`.
Is there a metric which returns the total number of requests which errored out? If no, can this be added?

**Comment by ninehills** [comment]
Check the metrics: ratelimit.service.call.should_rate_limit.*

- redis_error
- service_error

https://github.com/envoyproxy/ratelimit/blob/main/src/stats/manager_impl.go#L40

**Comment by kewshah4** [comment]
Thanks @ninehills, from what I understand `service_error` only includes errors related to loading config, and `redis_error` only includes errors related to executing Redis commands. Can there be other errors which are not accounted for?

**Comment by ninehills** [comment]
see https://github.com/envoyproxy/ratelimit/blob/main/src/service/ratelimit.go#L287

It only has two error types. Other errors will panic and crash. So if you want to count all error requests, use ratelimit.service.call.should_rate_limit.* .

**Comment by ninehills** [comment]
And I suggest using `prom/statsd-exporter` to provide Prometheus metrics with followed config file

https://github.com/envoyproxy/ratelimit/blob/main/examples/prom-statsd-exporter/conf.yaml

Docker start command:
```
docker run -d -p 9102:9102 -p 9125:9125 -p 9125:9125/udp -v $PWD/examples/prom-statsd-exporter/conf.yaml:/tmp/conf.yaml prom/statsd-exporter --statsd.mapping-config=/tmp/conf.yaml
```

Then set `STATSD_PORT=9125` to ratelimit process

```
  - match: "ratelimit.service.call.should_rate_limit.*"
    name: "ratelimit_service_should_rate_limit_error"
    match_metric_type: counter
    labels:
      err_type: "$1"
```

The metric `ratelimit_service_should_rate_limit_error` is error requests count with err_type label.
