### ISSUE TITLE
Multiple descriptor with AND operator 

### ISSUE THREAD

**Issue by rvgud** [envoyproxy/ratelimit#390]
Our requirement is to put a rate limit as below:

1. Allow 600 req/day
2. Above 600 req should be across the day. Meaning maybe 60 req per minute.

I have tried below descriptor definition but it seems its is putting multiple rules with OR operator.
`
domain: test-domain
descriptors:
    - key: USERID
      value: "TEMP_USER"
      rate_limit:
        requests_per_unit: 600
        unit: day
    - key: USERID
      value: "TEMP_USER"
      rate_limit:
        requests_per_unit: 60
        unit: hour`

With above config, it is allowing all the day limit which is 600 req, in first hour of the day as well since it matches the first rules and ignores the second rules.

Idea here is to not allow customers to send all the request of daily limit in a short period of time and over-flood the server. Instead allow a small portion of their daily limit per hour. 

I couldn't achieve it using multiple combinations of descriptors, so wondering if it even supported.

**Comment by m-rcl** [comment]
I think your requirement is the same one as #190
