### ISSUE TITLE
the last release 1.4.0 is 2 years old

### ISSUE THREAD

**Issue by kkcmadhu** [envoyproxy/ratelimit#404]
the last release was made around march 2020..
there are quite some active development after that,
any idea why no new release were made?

Should one take the builds from main, is the main brach stuff production ready?

**Comment by Stoakes** [comment]
Hello,

I'm not maintaining this project, but you'll find more informations around ratelimit & the question of releases on https://github.com/envoyproxy/ratelimit/issues/257
