### ISSUE TITLE
Timeouts for envoy while contacting Ratelimiter

### ISSUE THREAD

**Issue by aalokjha-gits** [envoyproxy/ratelimit#419]
- We are using AWS NLB that is mapped to all the ratelimiter instances.

- We are facing issue with lot of timeouts why envoy calls ratelimiter, which leads to leak/drop of requests.

![image](https://user-images.githubusercontent.com/28060283/236806217-3882eae0-7735-488f-9989-10bdc3ca13a4.png)

Envoy configuration that we are having

```shell
USE_STATSD=true
LOG_LEVEL=debug
GRPC_MAX_CONNECTION_AGE=4m
GRPC_MAX_CONNECTION_AGE_GRACE=5s
REDIS_SOCKET_TYPE=tcp
REDIS_PIPELINE_WINDOW=150us
REDIS_TYPE=cluster
REDIS_URL=****************
RUNTIME_ROOT=*************
RUNTIME_SUBDIRECTORY=************
RUNTIME_WATCH_ROOT=false
PORT=8090
GRPC_PORT=8091
```

**Comment by zdutta** [comment]
Hey @aalokjha-gits ! Were you able to resolve this issue? I am facing the same issues in my current envoy set up.
