### ISSUE TITLE
Error in rate-limit integration tests

### ISSUE THREAD

**Issue by vsabella** [envoyproxy/ratelimit#449]
When running `make integration_tests`

ratelimit-ratelimit-1    | time="2023-09-20T04:30:36Z" level=debug msg="returning normal response"
ratelimit-tester-1       | Length: 0
ratelimit-tester-1       | 
ratelimit-tester-1       | Overlimit should be 1
ratelimit-tester-1       | 
ratelimit-tester-1       | Failed file /test/scripts/value-included-in-stats-key-when-unspecified.sh
ratelimit-tester-1 exited with code 1

**Comment by DaniilKoshelev** [comment]
Had to add timeout (sleep) between API calls to fix this error
