### ISSUE TITLE
detailed_metric support for dynamic config using xDS server

### ISSUE THREAD

**Issue by akondapuram** [envoyproxy/ratelimit#461]
Hi all, we have a scenario where we would like to have the `detailed_metric` support for the dynamic config as well. 
The open source solution using [static limits](https://github.com/envoyproxy/ratelimit/blob/main/src/config/config_impl.go#L34) supports a feature called `detailed_metric` in the descriptor of the ratelimit config for extending the metrics for unspecified values. However, the dynamic config using xDS Server ([xds-config](https://github.com/envoyproxy/ratelimit/blob/main/src/config/config_xds.go)) doesn't support this field. This is the [RatelimitConfig proto](https://github.com/envoyproxy/go-control-plane/blob/main/ratelimit/config/ratelimit/v3/rls_conf.pb.go) it uses.

Could we please add the `detailed_metric` field to dynamic config as well? Thank you!

**Comment by akondapuram** [comment]
Created 2 PRs 
1. For the [go-control-plane repo](https://github.com/envoyproxy/go-control-plane/pull/841). This has to be checked in first as the second PR has a dependency on this one. 
2. For the [ratelimit repo.](https://github.com/envoyproxy/ratelimit/pull/465)

**Comment by dmi3zkm** [comment]
Hey @envoyproxy/ratelimit-maintainers
Could you please review this PR?

**Comment by akondapuram** [comment]
The change has been merged. Thanks!
