### ISSUE TITLE
response time is too long when Redis is DOWN

### ISSUE THREAD

**Issue by barvinsa** [envoyproxy/ratelimit#462]
Issue when the rate limit service couldn't reach the Redis database.
With failure_mode_deny: false 
traffic to service is allowed but takes too long to respond as if every request waits for Redis to time out before processing it,

With redis is UP: curl response time in milliseconds :
Code 200, Time 0.06
Code 429, Time 0.13
Code 429, Time 0.04

If redis is DOWN: curl response time takes seconds or 10 seconds
Code 200, Time 1.23
Code 200, Time 1.20
Code 200, Time 10.12

REDIS_HEALTH_CHECK_ACTIVE_CONNECTION: "true" doesn't make a difference.

Bring ratelimit service down if redis health check fails would be a solution

**Comment by pjjwpc** [comment]
应该是mediocregopher/radix/v3 项目的底层读写超时时间，它默认10秒，ratelimit 没有设置读写超时配置的地方，我们可以自己实现一个

**Comment by pjjwpc** [comment]
typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.ratelimit.v3.RateLimit
            domain: httpbin-1
            failure_mode_deny: false
            timeout: 10s
The configurations here impact the speed.

**Comment by barvinsa** [comment]
Reduced timeout: 1s

Running curls:
Response  Code: 200 Time: 0.04
Response  Code: 200 Time: 0.24
Response  Code: 200 Time: 0.04

After Redis was scaled down - request time increased to 1s
Response  Code: 200 Time: 1.04
Response  Code: 200 Time: 1.15
Response  Code: 200 Time: 1.19

If rate-limit could ignore redis while health check flagging redis as down, that would be a solution.
As of now, rate-limit waits for redis to time-out before serving the request.

**Comment by pjjwpc** [comment]
You seem to have confused two timeout mechanisms, one being the timeout for calling the rate-limit service, and the other being the timeout for internal calls to Redis within the rate-limit service. If you want to achieve faster returns in case the rate-limit service is unavailable, you should set the timeout at the rate-limit filter, which is set to a default of 20ms.

**Comment by Moisi** [comment]
@barvinsa

Hey! How did you solve it? 
We're seeing the same this over here!
