### ISSUE TITLE
Public docker image

### ISSUE THREAD

**Issue by akalini** [envoyproxy/ratelimit#57]
Is there a public docker image that we can use? I checked dockerhub.com and there are many images there built by 3rd parties, but I could not find one from Lyft.

**Comment by stevesloka** [comment]
@akalini I ran into the same question. To get started, I have a PR which adds a Dockerfile to let the image be built (See #58).

**Comment by stevesloka** [comment]
Now that #58 is in, could we have an automatic build for this? I'm happy to help set that up, but not sure what backend infrastructure is available. For now I'm going to build my own image, but would be nice to have a shared one to reference.

**Comment by stevenscg** [comment]
@stevesloka This seems to be one of the few envoy-related projects missing from the lyft namespace on docker hub. Like you, I'm building my own as a base, but would certainly use a public "official" one if it existed.

**Comment by psalaberria002** [comment]
Any news on this issue? It would be great to have it publicly available.

**Comment by junr03** [comment]
@psalaberria002 we have not allocated resources to make this happen. However, this should not be too hard to accomplished. If there is someone around that would like to setup the CI plumbing to do so (push image to dockerhub on commit to master) we can work with them to get dockerhub credentials on CI to push to Lyft's org.

**Comment by psalaberria002** [comment]
Travis build, test and deploy on merge to master? Do you have any recommended tool or aproach? If you could share an example Lyft repo where an image is pushed to Dockerhub that would be awesome @junr03 .

**Comment by sachdeva-vivek** [comment]
I am trying to build my docker image locally but getting: 

`
Step 5/13 : COPY vendor vendor
COPY failed: stat /var/lib/docker/tmp/docker-builder548667671/vendor: no such file or directory
`

I tried to comment out the above line but then I later I get:

`Step 9/12 : RUN CGO_ENABLED=0 GOOS=linux go build -o /usr/local/bin/ratelimit -ldflags="-w -s" -v github.com/lyft/ratelimit/src/service_cmd
 ---> Running in 832d6140af6f
src/service_cmd/runner/runner.go:10:2: cannot find package "github.com/lyft/ratelimit/proto/ratelimit" in any of:
	/go/src/github.com/lyft/ratelimit/vendor/github.com/lyft/ratelimit/proto/ratelimit (vendor tree)
	/usr/local/go/src/github.com/lyft/ratelimit/proto/ratelimit (from $GOROOT)
	/go/src/github.com/lyft/ratelimit/proto/ratelimit (from $GOPATH)`

Any ideas?

**Comment by stevesloka** [comment]
Catching up on this issue again, happy to help out. 

I see a bunch of work was done in #105 so I don't want to duplicate the effort. 

It seems the work steps are:

1. Move to `envoyproxy` org?
2. Update to go modules
3. Update Deps (go version in dockerfile, etc)
4. Update Travis build to create an image + push

**Comment by mattklein123** [comment]
Sorry this fell off my radar. I will start the discussion internally at Lyft on moving this project to the Envoy org.

**Comment by mattklein123** [comment]
@stevesloka we are good to do the transfer. I will get this going this week.

**Comment by stevesloka** [comment]
Thanks @mattklein123! I'll put some PRs together. 😀

**Comment by dragonly** [comment]
It's amazing that I am wondering for a rate limit solution and found this issue brought back to life! Thank you guys and I'm really looking forward for an official docker image!

**Comment by stevesloka** [comment]
Thanks for merging @mattklein123, I've got some GitHub actions coming next for building/pushing images.
