### ISSUE TITLE
Consider using github releases/tags?

### ISSUE THREAD

**Issue by amdawson** [envoyproxy/ratelimit#607]
Hi team,
I'm at Chainguard and we build distroless container images of many OSS projects including ratelimit. We try to pick up all patches and releases as fast as possible so our customers can stay up to date. We would like to ask if this project would consider using release versioning or tags through github again.  We monitor project repos for new releases or tags to automate our builds and apply container image tags. 

I know you build your own containers and host them at dockerhub, but we could automatically build secure, minimal containers for every release that we host at images.chainguard.dev and also dockerhub/chainguard, which you could link to or distribute as well.

Hoping you'll consider adding tags/release versions, thank you!

**Comment by sfc-gh-jelsesiy** [comment]
@mattklein123 @amdawson Can we please consider reopen this issue and discuss long-term solutions that allow better release management in this repo? Thank you!

Relates to https://github.com/envoyproxy/ratelimit/issues/174
