### ISSUE TITLE
Do we have K8s CRD as config source?

### ISSUE THREAD

**Issue by SpecialYang** [envoyproxy/ratelimit#633]
Now, how can we use k8s crd to define ratelimit config?

**Comment by birdayz** [comment]
Not ready made available, but you can do yourself: implement XDS SOTW API and read the data from CRs. Example: https://github.com/envoyproxy/ratelimit/tree/main/examples/xds-sotw-config-server

it's a great idea though

**Comment by zirain** [comment]
> Not ready made available, but you can do yourself: implement XDS SOTW API and read the data from CRs. Example: https://github.com/envoyproxy/ratelimit/tree/main/examples/xds-sotw-config-server
> 
> it's a great idea though

Yeah, that's what EG did.
