### ISSUE TITLE
How can I apply Two Rate limits on the same Key Value pair?

### ISSUE THREAD

**Issue by kkasbi** [envoyproxy/ratelimit#693]
I basically want to apply multiple limits to get, post etc methods. 

> `          - descriptors:
>               - descriptors:
>                   - key: method
>                     rate_limit:
>                       requests_per_unit: 1000
>                       unit: 3
>                       unlimited: false
>                     value: get
>                   - key: method
>                     rate_limit:
>                       requests_per_unit: 2
>                       unit: 1
>                       unlimited: false
>                     value: get
>                   - key: method
>                     rate_limit:
>                       requests_per_unit: 400
>                       unit: 3
>                       unlimited: false
>                     value: post
>                   - key: method
>                     rate_limit:
>                       requests_per_unit: 1
>                       unit: 1
>                       unlimited: false
>                     value: post
>                 key: path
>                 rate_limit:
>                   requests_per_unit: 1000
>                   unit: 1
>                   unlimited: false
>                 value: /api/v1/subpath`

But the above give the below error, 

duplicate descriptor composite key 'apis.tenant.destination_cluster_cloud.net.path_/prd/api/v1/subpath.method_get

Any possible solutions to this?

**Comment by zirain** [comment]
use different domain?
