### ISSUE TITLE
How to use a hash of descriptor instead of a raw descriptor?

### ISSUE THREAD

**Issue by andrii-korotkov-verkada** [envoyproxy/ratelimit#699]
Hello,
I hope your day is going well.
There's a use case of rate limiting per auth token (stored in a header), which effectively means rate limit per caller. However, it's not desired to store a raw token in Redis as a part of a key. What's the best way to get a hashed value of the auth token to be used as a descriptor?
Thanks.

**Comment by jespersoderlund** [comment]
How about creating the hash in a lua-script in your envoy config and put it into a dynamic variable and use that to ratelimit on?
